functionality:
  name: initialize
  namespace: api
  __inherits__:
    - ../../variables/api-arguments.yaml
    - ../../variables/io-arguments.yaml
  arguments:
    - name: --conf
      type: file
      default: etc/api.conf
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: native
