functionality:
  name: initialize
  namespace: api
  __inherits__: ../../variables/api-arguments.yaml
  arguments:
    - name: --conf
      type: file
      default: etc/initialize.conf
    # - name: --db
    #   type: file
    #   default: /Users/toni/Dropbox/_GSK/2022/output-data/
    # - name: --version
    #   type: integer
    #   default: 0
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: native
