project:
  type: website
  output-dir: docs
  render:
    - README.md
    - usage.qmd
    - installation.qmd
    - troubleshooting.qmd

website:
  title: "LuciusOperations"
  navbar:
    left:
      - href: README.md
        text: Home
      - href: installation.qmd
        text: Installation 
      - href: usage.qmd
        text: Usage
      - href: troubleshooting.qmd
        text: Troubleshooting

format:
  html:
    theme: flatly
    toc: true

execute:
  freeze: auto  # re-render only when source changes
