project:
  type: website
  output-dir: docs

website:
  title: "docs"
  navbar:
    left:
      - href: docs/index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
