functionality:
  name: remove_context
  namespace: api
  arguments:
    __inherits__: ../../variables/api-arguments.yaml
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: native
