functionality:
  name: create_context
  namespace: processing
  __inherits__: ../../variables/processing-arguments.yaml
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: native
